from syncdb import SyncDB
from filedb import FileDB
import threading
import logging

FORMAT = '%(asctime)s.%(msecs)03d - %(message)s'
DATEFMT = '%H:%M:%S'


def main():
    logging.debug("Starting tests for Multithreading")
    db = SyncDB(FileDB(), True)
    logging.debug("\n--------------------------------------------------------\n")
    logging.info("testing simple write perms")
    t1 = threading.Thread(target=SyncDB.set_value, args=(db, "test1", 1))
    t1.start()
    t1.join()
    logging.info("test successful")
    logging.debug("\n--------------------------------------------------------\n")
    logging.info("testing simple read perms")
    t1 = threading.Thread(target=SyncDB.get_value, args=(db, "test1"))
    t1.start()
    t1.join()
    logging.info("test successful")
    logging.debug("\n--------------------------------------------------------\n")
    logging.info("testing read blocks writing")
    t1 = threading.Thread(target=SyncDB.get_value, args=(db, "test1"))
    t2 = threading.Thread(target=SyncDB.set_value, args=(db, "test2", 2))
    t1.start()
    t2.start()
    t1.join()
    t2.join()
    logging.info("test successful")
    logging.debug("\n--------------------------------------------------------\n")
    logging.info("testing write blocks reading")
    t1 = threading.Thread(target=SyncDB.set_value, args=(db, "test3", 3))
    t2 = threading.Thread(target=SyncDB.get_value, args=(db, "test2"))
    t1.start()
    t2.start()
    t1.join()
    t2.join()
    logging.info("test successful")
    logging.debug("\n--------------------------------------------------------\n")
    logging.info("testing multi reading perms possible")
    t1 = threading.Thread(target=SyncDB.get_value, args=(db, "test3"))
    t2 = threading.Thread(target=SyncDB.get_value, args=(db, "test4"))
    t1.start()
    t2.start()
    t1.join()
    t2.join()
    logging.info("test successful")
    logging.debug("\n--------------------------------------------------------\n")
    logging.info("testing delete")
    t1 = threading.Thread(target=SyncDB.delete_value, args=(db, "test1"))
    t2 = threading.Thread(target=SyncDB.get_value, args=(db, "test1"))
    t3 = threading.Thread(target=SyncDB.set_value, args=(db, "test1", 1))
    t1.start()
    t2.start()
    t3.start()
    t1.join()
    t2.join()
    t3.join()
    logging.debug("\n--------------------------------------------------------\n")
    logging.info("testing load")
    t1 = threading.Thread(target=SyncDB.get_value, args=(db, "test1"))
    t2 = threading.Thread(target=SyncDB.get_value, args=(db, "test3"))
    t3 = threading.Thread(target=SyncDB.set_value, args=(db, "load", "abcabc"))
    t1.start()
    t2.start()
    t3.start()
    t1.join()
    t2.join()
    t1 = threading.Thread(target=SyncDB.get_value, args=(db, "load"))
    t2 = threading.Thread(target=SyncDB.get_value, args=(db, "test2"))
    t1.start()
    t2.start()
    t3.join()
    t1.join()
    t2.join()
    logging.info("test successful")


if __name__ == '__main__':
    logging.basicConfig(filename="ThreadTest.log", filemode="a", level=logging.DEBUG, format=FORMAT, datefmt=DATEFMT)
    main()
